dist: xenial
sudo: required
language: python
python: 3.6
cache:
  directories:
    - ${HOME}/.cache/pip
services:
  - docker
install:
  - docker-compose up -d
  - echo "https://${GITHUB_TOKEN}:x-oauth-basic@github.com" > ~/.git-credentials
  - git config --global credential.helper store
  - pip install -r requirements.txt
  - pip install -e .[dev]
  - pip install codecov
  - make create-user
script:
  - pytest
  - pycodestyle
after_success:
  - codecov
