dist: xenial
sudo: required
language: python
python: 3.6
cache:
  directories:
    - $HOME/.cache/pip
services:
  - docker
install:
  - docker-compose up -d
  - pip install -e git+https://$GITHUB_TOKEN:x-oauth-basic@github.com/openstax/biglearn-sparfa-algs.git/@master#egg=sparfa-algs
  - pip install -e .[dev]
  - pip install codecov
  - make create-user
script:
  - pytest
  - pycodestyle
after_success:
  - codecov
