dist: xenial
sudo: required
language: python
python: 3.6
cache:
  directories:
    - $HOME/.cache/pip
services:
  - docker
install:
  - docker-compose up -d
  - pip install --process-dependency-links -e .[ci]
  - make create-user
script:
  - pytest
after_success:
  - codecov
