language: python
python:
  - "3.6"

dist: trusty
sudo: false

addons:
  postgresql: "9.6"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

services:
  - postgresql

cache:
  directories:
    - $HOME/.cache/pip

# command to install dependencies

before_install:
  - python setup.py bdist_wheel --universal
install:
  - pip install -e .[dev]
  - pip install codecov

script:
  - python setup.py test

after_success:
  - codecov
