language: python
python:
  - "3.7"

dist: xenial
sudo: required

addons:
  postgresql: "9.6"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

services:
  - postgresql

cache:
  directories:
    - $HOME/.cache/pip

# command to install dependencies

install:
  - pip install --process-dependency-links .[dev]
  - pip install codecov

script:
  - python setup.py test

after_success:
  - codecov
