branches:
  only: master
dist: xenial
language: python
python: 3.7
services:
  - docker
cache:
  directories:
    - ${HOME}/.cache/pip
install:
  - docker-compose up -d
  - echo "https://${GITHUB_TOKEN}:x-oauth-basic@github.com" > ~/.git-credentials
  - echo '[url "https://github.com/"]' >> ~/.gitconfig
  - echo "        insteadOf = git@github.com:" >> ~/.gitconfig
  - git config --global credential.helper store
  - pip install -r requirements.txt
  - pip install -e .[dev]
  - pip install codecov
  - make create-user
script:
  - pytest
  - pycodestyle
after_success:
  - codecov
