version: '2'
services:
  db:
    image: postgres:9.6
    ports:
      - '127.0.0.1:5445:5432'
  rabbit:
    image: rabbitmq:3.6-management-alpine
    ports:
      - '127.0.0.1:5672:5672'
      - '127.0.0.1:15672:15672'
