"""added ecosystem_uuid, assignmend_uuids and superseded_by_uuid columns to ecosystem_matrices table

Revision ID: 2a6028ae0b54
Revises: 1fd4e54a1638
Create Date: 2019-10-04 16:55:05.361473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a6028ae0b54'
down_revision = '1fd4e54a1638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecosystem_matrices', sa.Column('ecosystem_uuid', postgresql.UUID(), nullable=True))
    op.add_column('ecosystem_matrices', sa.Column('assignment_uuids', postgresql.ARRAY(postgresql.UUID()), server_default='{}', nullable=False))
    op.add_column('ecosystem_matrices', sa.Column('superseded_by_uuid', postgresql.UUID(), nullable=True))
    op.execute('UPDATE "ecosystem_matrices" SET "ecosystem_uuid" = "uuid"')
    op.alter_column('ecosystem_matrices', 'ecosystem_uuid', nullable=False)
    op.create_index(op.f('ix_ecosystem_matrices_ecosystem_uuid'), 'ecosystem_matrices', ['ecosystem_uuid'], unique=False)
    op.create_index(op.f('ix_ecosystem_matrices_assignment_uuids'), 'ecosystem_matrices', ['assignment_uuids'], unique=False)
    op.create_index(op.f('ix_ecosystem_matrices_superseded_by_uuid'), 'ecosystem_matrices', ['superseded_by_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ecosystem_matrices_superseded_by_uuid'), table_name='ecosystem_matrices')
    op.drop_index(op.f('ix_ecosystem_matrices_assignment_uuids'), table_name='ecosystem_matrices')
    op.drop_index(op.f('ix_ecosystem_matrices_ecosystem_uuid'), table_name='ecosystem_matrices')
    op.drop_column('ecosystem_matrices', 'superseded_by_uuid')
    op.drop_column('ecosystem_matrices', 'assignment_uuids')
    op.drop_column('ecosystem_matrices', 'ecosystem_uuid')
    # ### end Alembic commands ###
