"""added course_id to course_events table

Revision ID: 4f03336cb41c
Revises: 1d14fd1ea8d9
Create Date: 2017-06-06 14:47:49.329404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f03336cb41c'
down_revision = '1d14fd1ea8d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_events', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course_events', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_events', type_='foreignkey')
    op.drop_column('course_events', 'course_id')
    # ### end Alembic commands ###
