"""initial schema

Revision ID: 59bc7091d69b
Revises: 
Create Date: 2018-10-16 13:56:39.165853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59bc7091d69b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('ecosystem_matrices',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('ecosystem_uuid', postgresql.UUID(), nullable=False),
    sa.Column('W_NCxNQ', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('d_NQx1', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('C_idx_by_id', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('Q_idx_by_id', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('H_mask_NCxNQ', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_ecosystem_matrices_ecosystem_uuid'), 'ecosystem_matrices', ['ecosystem_uuid'], unique=True)
    op.create_table('ecosystems',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('page_exercises',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('ecosystem_uuid', postgresql.UUID(), nullable=False),
    sa.Column('page_uuid', postgresql.UUID(), nullable=False),
    sa.Column('exercise_uuid', postgresql.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_page_exercises_ecosystem_uuid'), 'page_exercises', ['ecosystem_uuid'], unique=False)
    op.create_index('ix_page_exercises_on_exercise_uuid_and_ecosystem_uuid', 'page_exercises', ['exercise_uuid', 'ecosystem_uuid'], unique=True)
    op.create_index(op.f('ix_page_exercises_page_uuid'), 'page_exercises', ['page_uuid'], unique=False)
    op.create_table('responses',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('course_uuid', postgresql.UUID(), nullable=False),
    sa.Column('ecosystem_uuid', postgresql.UUID(), nullable=False),
    sa.Column('trial_uuid', postgresql.UUID(), nullable=False),
    sa.Column('student_uuid', postgresql.UUID(), nullable=False),
    sa.Column('exercise_uuid', postgresql.UUID(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('is_real_response', sa.Boolean(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_responses_course_uuid'), 'responses', ['course_uuid'], unique=False)
    op.create_index(op.f('ix_responses_ecosystem_uuid'), 'responses', ['ecosystem_uuid'], unique=False)
    op.create_index(op.f('ix_responses_exercise_uuid'), 'responses', ['exercise_uuid'], unique=False)
    op.create_index(op.f('ix_responses_student_uuid'), 'responses', ['student_uuid'], unique=False)
    op.create_index(op.f('ix_responses_trial_uuid'), 'responses', ['trial_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_responses_trial_uuid'), table_name='responses')
    op.drop_index(op.f('ix_responses_student_uuid'), table_name='responses')
    op.drop_index(op.f('ix_responses_exercise_uuid'), table_name='responses')
    op.drop_index(op.f('ix_responses_ecosystem_uuid'), table_name='responses')
    op.drop_index(op.f('ix_responses_course_uuid'), table_name='responses')
    op.drop_table('responses')
    op.drop_index(op.f('ix_page_exercises_page_uuid'), table_name='page_exercises')
    op.drop_index('ix_page_exercises_on_exercise_uuid_and_ecosystem_uuid', table_name='page_exercises')
    op.drop_index(op.f('ix_page_exercises_ecosystem_uuid'), table_name='page_exercises')
    op.drop_table('page_exercises')
    op.drop_table('ecosystems')
    op.drop_index(op.f('ix_ecosystem_matrices_ecosystem_uuid'), table_name='ecosystem_matrices')
    op.drop_table('ecosystem_matrices')
    op.drop_table('courses')
    # ### end Alembic commands ###
