"""near-final schema

Revision ID: 69d4569a22a1
Revises: 
Create Date: 2017-06-21 15:24:55.125204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69d4569a22a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_uuid', postgresql.UUID(), nullable=False),
    sa.Column('exercise_uuid', postgresql.UUID(), nullable=False),
    sa.Column('ecosystem_uuid', postgresql.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('container_uuid', 'ecosystem_uuid', 'exercise_uuid')
    )
    op.create_index(op.f('ix_container_exercises_container_uuid'), 'container_exercises', ['container_uuid'], unique=False)
    op.create_index(op.f('ix_container_exercises_exercise_uuid'), 'container_exercises', ['exercise_uuid'], unique=False)
    op.create_table('containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(), nullable=True),
    sa.Column('ecosystem_uuid', postgresql.UUID(), nullable=False),
    sa.Column('container_cnx_identity', sa.String(length=50), nullable=True),
    sa.Column('container_parent_uuid', postgresql.UUID(), nullable=True),
    sa.Column('is_page_module', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('course_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('uuid', postgresql.UUID(), nullable=True),
    sa.Column('course_uuid', postgresql.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('event_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(), nullable=True),
    sa.Column('ecosystem_uuid', postgresql.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('ecosystem_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecosystem_uuid', postgresql.UUID(), nullable=False),
    sa.Column('exercise_uuid', postgresql.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecosystem_uuid', 'exercise_uuid')
    )
    op.create_index(op.f('ix_ecosystem_exercises_ecosystem_uuid'), 'ecosystem_exercises', ['ecosystem_uuid'], unique=False)
    op.create_table('ecosystems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(), nullable=True),
    sa.Column('group_uuid', postgresql.UUID(), nullable=False),
    sa.Column('los', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(), nullable=True),
    sa.Column('ecosystem_uuid', postgresql.UUID(), nullable=False),
    sa.Column('course_uuid', postgresql.UUID(), nullable=False),
    sa.Column('exercise_uuid', postgresql.UUID(), nullable=False),
    sa.Column('student_uuid', postgresql.UUID(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_responses_ecosystem_uuid'), 'responses', ['ecosystem_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_responses_ecosystem_uuid'), table_name='responses')
    op.drop_table('responses')
    op.drop_table('exercises')
    op.drop_table('ecosystems')
    op.drop_index(op.f('ix_ecosystem_exercises_ecosystem_uuid'), table_name='ecosystem_exercises')
    op.drop_table('ecosystem_exercises')
    op.drop_table('courses')
    op.drop_table('course_events')
    op.drop_table('containers')
    op.drop_index(op.f('ix_container_exercises_exercise_uuid'), table_name='container_exercises')
    op.drop_index(op.f('ix_container_exercises_container_uuid'), table_name='container_exercises')
    op.drop_table('container_exercises')
    # ### end Alembic commands ###
