"""added last_ecosystem_matrix_update_calculation_uuid column to ecosystems table

Revision ID: cd8b24e3a7de
Revises: 1c3848e662c2
Create Date: 2019-06-06 10:20:51.904180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd8b24e3a7de'
down_revision = '1c3848e662c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecosystems', sa.Column('last_ecosystem_matrix_update_calculation_uuid', postgresql.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ecosystems', 'last_ecosystem_matrix_update_calculation_uuid')
    # ### end Alembic commands ###
