"""added metadata_sequence_number columns to ecosystems table and courses table

Revision ID: d8109c51b21f
Revises: 401aba1f3839
Create Date: 2017-08-23 16:24:43.409935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8109c51b21f'
down_revision = '401aba1f3839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('metadata_sequence_number', sa.Integer(), nullable=True))
    op.execute('''
        WITH "course_row_numbers" AS (
          SELECT "courses"."id", ROW_NUMBER() OVER (ORDER BY "courses"."uuid") AS "row_number"
          FROM "courses"
        )
        UPDATE "courses"
        SET "metadata_sequence_number" = "course_row_numbers"."row_number"
        FROM "course_row_numbers"
        WHERE "course_row_numbers"."id" = "courses"."id"
    ''')
    op.alter_column('courses', 'metadata_sequence_number', nullable=False)
    op.create_index(op.f('ix_courses_metadata_sequence_number'), 'courses', ['metadata_sequence_number'], unique=True)

    op.add_column('ecosystems', sa.Column('metadata_sequence_number', sa.Integer(), nullable=True))
    op.execute('''
        WITH "ecosystem_row_numbers" AS (
          SELECT "ecosystems"."id", ROW_NUMBER() OVER (ORDER BY "ecosystems"."uuid") AS "row_number"
          FROM "ecosystems"
        )
        UPDATE "ecosystems"
        SET "metadata_sequence_number" = "ecosystem_row_numbers"."row_number"
        FROM "ecosystem_row_numbers"
        WHERE "ecosystem_row_numbers"."id" = "ecosystems"."id"
    ''')
    op.alter_column('ecosystems', 'metadata_sequence_number', nullable=False)
    op.create_index(op.f('ix_ecosystems_metadata_sequence_number'), 'ecosystems', ['metadata_sequence_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ecosystems_metadata_sequence_number'), table_name='ecosystems')
    op.drop_column('ecosystems', 'metadata_sequence_number')

    op.drop_index(op.f('ix_courses_metadata_sequence_number'), table_name='courses')
    op.drop_column('courses', 'metadata_sequence_number')
    # ### end Alembic commands ###
