"""added columns cnx_identity and parent_uuid to chapter table

Revision ID: defaa94f1f59
Revises: 335e1c1a96da
Create Date: 2017-05-30 10:50:19.871910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'defaa94f1f59'
down_revision = '335e1c1a96da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('container_cnx_identity', sa.String(length=50), nullable=True))
    op.add_column('containers', sa.Column('container_parent_uuid', postgresql.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('containers', 'container_parent_uuid')
    op.drop_column('containers', 'container_cnx_identity')
    # ### end Alembic commands ###
