"""renamed w_matrix table to ecosystem_matrices

Revision ID: ed73d83a350b
Revises: ef8b823c09f2
Create Date: 2017-07-07 10:36:24.390870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed73d83a350b'
down_revision = 'ef8b823c09f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecosystem_matrices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecosystem_uuid', postgresql.UUID(), nullable=False),
    sa.Column('w_matrix', sa.String(), nullable=False),
    sa.Column('d_matrix', sa.String(), nullable=False),
    sa.Column('C_idx_by_id', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('Q_idx_by_id', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('L_idx_by_id', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecosystem_uuid')
    )
    op.drop_table('w_matrix')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('w_matrix',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ecosystem_uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('C_id_by_idx', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('L_id_by_idx', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('Q_id_by_idx', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('d_matrix', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('w_matrix', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='w_matrix_pkey'),
    sa.UniqueConstraint('ecosystem_uuid', name='w_matrix_ecosystem_uuid_key')
    )
    op.drop_table('ecosystem_matrices')
    # ### end Alembic commands ###
