"""refactored w_matrix table for saving numpy arrays and serialized json

Revision ID: ef8b823c09f2
Revises: 50e4689bffe7
Create Date: 2017-07-06 13:48:18.430120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef8b823c09f2'
down_revision = '50e4689bffe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('d_matrix')
    op.add_column('w_matrix', sa.Column('C_id_by_idx', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    op.add_column('w_matrix', sa.Column('L_id_by_idx', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('w_matrix', sa.Column('Q_id_by_idx', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    op.add_column('w_matrix', sa.Column('d_matrix', sa.String(), nullable=False))
    op.add_column('w_matrix', sa.Column('w_matrix', sa.String(), nullable=False))
    op.drop_constraint('w_matrix_ecosystem_uuid_exercise_uuid_page_module_uuid_key', 'w_matrix', type_='unique')
    op.create_unique_constraint(None, 'w_matrix', ['ecosystem_uuid'])
    op.drop_column('w_matrix', 'exercise_uuid')
    op.drop_column('w_matrix', 'score')
    op.drop_column('w_matrix', 'page_module_uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('w_matrix', sa.Column('page_module_uuid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.add_column('w_matrix', sa.Column('score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('w_matrix', sa.Column('exercise_uuid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'w_matrix', type_='unique')
    op.create_unique_constraint('w_matrix_ecosystem_uuid_exercise_uuid_page_module_uuid_key', 'w_matrix', ['ecosystem_uuid', 'exercise_uuid', 'page_module_uuid'])
    op.drop_column('w_matrix', 'w_matrix')
    op.drop_column('w_matrix', 'd_matrix')
    op.drop_column('w_matrix', 'Q_id_by_idx')
    op.drop_column('w_matrix', 'L_id_by_idx')
    op.drop_column('w_matrix', 'C_id_by_idx')
    op.create_table('d_matrix',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ecosystem_uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('exercise_uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('delta', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='d_matrix_pkey'),
    sa.UniqueConstraint('ecosystem_uuid', 'exercise_uuid', name='d_matrix_ecosystem_uuid_exercise_uuid_key')
    )
    # ### end Alembic commands ###
