"""added w_matrix table

Revision ID: f09792f80a57
Revises: 69d4569a22a1
Create Date: 2017-06-27 10:46:31.969668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f09792f80a57'
down_revision = '69d4569a22a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('w_matrix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecosystem_uuid', postgresql.UUID(), nullable=False),
    sa.Column('page_module_uuid', postgresql.UUID(), nullable=False),
    sa.Column('exercise_uuid', postgresql.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecosystem_uuid', 'exercise_uuid', 'page_module_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('w_matrix')
    # ### end Alembic commands ###
